FROM jaegertracing/jaeger:2.3.0
COPY config.yaml /etc/jaeger/config.yaml
HEALTHCHECK \
    --interval=1s \
    --timeout=1s \
    --start-period=1s \
    --retries=60 \
    CMD wget -q --header='Content-Type:application/json' -O - http://localhost:14269/health | grep "Server available"
